Add features and fix
aXenDeveloper/sourcebans-web-theme-fluent pull request #50
Opened 2022-04-11 15:07 UTC by Rushaway

Add Features as ban origin of bans / comms
Imrpove UI 
Fix some text errors
Fix dashboard

2022-04-11 15:16 UTC, aXenDeveloper requested changes
Please use prettier plugin for better formatting code.

2022-04-11 19:39 UTC, aXenDeveloper commented
Please remove `center` tag form this PR.

2022-04-11 20:43 UTC, Rushaway commented
> Please remove all `center` tag form this PR.

Done.

2022-04-11 21:31 UTC, Rushaway commented
https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/pull/50/commits/05b9b08b6e445310f086821c83d8435cf1cd38c5 is fixing https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/issues/51

2022-04-14 02:45 UTC, crashzk commented
I believe it can be merged now, right @aXenDeveloper.

@Rushaway I just have a question regarding GameTracker support. If the server is not registered in GameTracker, what happens? Doesn't show anything or shows an error?

2022-04-18 09:12 UTC, Rushaway commented
@crashzk It will show a banner of GameTracker who said the IP isn't registered in GameTracker.

2022-04-18 11:14 UTC, Caaine commented
not good :S

2022-04-18 14:33 UTC, crashzk commented
> @crashzk It will show a banner of GameTracker who said the IP isn't registered in GameTracker.

I understand, I believe that the support for GameTracker is good, my opinion is that it should have it, but give it a way for the user to have control over it in the end, he chooses in the sourcebans options whether to activate it or not, as he has the option to show the admin that banned or not to players.

In any case, it is already a good start to have support for it.

2022-04-18 16:29 UTC, Rushaway commented
@crashzk Can be done, but need to edit the core file of Sourcebanspp.
It's a theme feature, not a global support from Sourcebanspp. So will not be implanted until sourcebanspp add this feature too as native.
People are free to remove or comments this code part.

2022-04-18 19:07 UTC, crashzk commented
> @crashzk Can be done, but need to edit the core file of Sourcebanspp. It's a theme feature, not a global support from Sourcebanspp. So will not be implanted until sourcebanspp add this feature too as native. People are free to remove or comments this code part.

I see, they've actually done a PR on sourcebans-pp too: https://github.com/sbpp/sourcebans-pp/pull/718

In any case for me even without having this feature I would still use it.

2022-04-21 09:18 UTC, aXenDeveloper requested changes

2022-04-21 09:18 UTC, aXenDeveloper commented on sourcebans-web-theme-fluent/page_servers.tpl
> +                                    <p class="responsive_show:desktop" align="center"><a href="https://www.gametracker.com/server_info/{$server.ip}:{$server.port}/"><img style="width: auto; height: a
Delete this. Not everyone wants this functionality.

Gametracker is very slow to load which may slow down the page loading speed

2022-04-29 19:38 UTC, aXenDeveloper approved these changes

2022-04-29 19:39 UTC, merged